import cherry from "../images/Cherry.png";
import bakedFish from "../images/Baked_Fish.png";
import goldBar from "../images/Gold_Bar.png";
import Glacierfish from "../images/Glacierfish.png";
import Grape from "../images/Grape.png";
import Lionfish from "../images/Lionfish.png";
import Mutant_Carp from "../images/Mutant_Carp.png";
import Pineapple from "../images/Pineapple.png";
import Pink_Cake from "../images/Pink_Cake.png";
import Prehistoric_Tibia from "../images/Prehistoric_Tibia.png";
import Rainbow_Trout from "../images/Rainbow_Trout.png";
import Strawberry from "../images/Strawberry.png";
import Blank from "../images/Blank.png";
import Spook_Fish from "../images/Spook_Fish.png";

export const slotArray = [
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  cherry,
  bakedFish,
  bakedFish,
  bakedFish,
  bakedFish,
  bakedFish,
  bakedFish,
  bakedFish,
  bakedFish,
  bakedFish,
  bakedFish,
  bakedFish,
  bakedFish,
  bakedFish,
  bakedFish,
  bakedFish,
  goldBar,
  goldBar,
  goldBar,
  goldBar,
  Glacierfish,
  Glacierfish,
  Glacierfish,
  Glacierfish,
  Glacierfish,
  Glacierfish,
  Glacierfish,
  Glacierfish,
  Glacierfish,
  Strawberry,
  Strawberry,
  Strawberry,
  Grape,
  Grape,
  Grape,
  Lionfish,
  Lionfish,
  Lionfish,
  Pineapple,
  Pineapple,
  Pineapple,
  Pineapple,
  Mutant_Carp,
  Mutant_Carp,
  Mutant_Carp,
  Mutant_Carp,
  Mutant_Carp,
  Mutant_Carp,
  Mutant_Carp,
  Pink_Cake,
  Pink_Cake,
  Pink_Cake,
  Prehistoric_Tibia,
  Rainbow_Trout,
  Spook_Fish,
];

export const payoutTable = [
  2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5,
  5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 10, 10, 10, 10, 10, 10, 25, 25, 25,
  25, 25, 25, 25, 25, 25, 25, 25, 50, 50, 50, 75, 100, 500,
];
